name: Setup Toolchain

inputs:
  toolchain:
    description: 'Toolchain name'
    required: true
  toolchain_url:
    description: 'Toolchain URL or version'
    required: false

outputs:
  build_option:
    description: 'Build option for the toolchain e.g --toolchain clang'
    value: ${{ steps.set-toolchain-option.outputs.build_option }}

runs:
  using: "composite"
  steps:
    - name: Install ARM GCC
      if: inputs.toolchain == 'arm-gcc'
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
#        release: '12.3.Rel1'
        release: '11.2-2022.02'

    - name: Pull ESP-IDF docker
      if: inputs.toolchain == 'esp-idf'
      uses: ./.github/actions/setup_toolchain/espressif
      with:
        toolchain: ${{ inputs.toolchain }}
        toolchain_url: ${{ inputs.toolchain_url }}

    - name: Download Toolchain
      if: >-
        inputs.toolchain != 'arm-gcc' &&
        inputs.toolchain != 'arm-iar' &&
        inputs.toolchain != 'esp-idf'
      uses: ./.github/actions/setup_toolchain/download
      with:
        toolchain: ${{ inputs.toolchain }}
        toolchain_url: ${{ inputs.toolchain_url }}
