name: Build CMake

on:
  push:
    paths:
      - 'src/**'
      - 'ports/**'
      - '!ports/espressif/**'
      - 'lib/**'
      - '.github/workflows/build_cmake.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'ports/**'
      - '!ports/espressif/**'
      - 'lib/**'
      - '.github/workflows/build_cmake.yml'
  repository_dispatch:
  release:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # ---------------------------------------
  # Build ARM family
  # ---------------------------------------
  ARM:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
        # Alphabetical order by family
        - 'metro_m7_1011'
        # - 'stm32f303disco' # overflows flash
        - 'stm32f411ve_discovery'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-tags: true

    - name: Install ARM GCC
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '11.2-2022.02'

    - name: Get Dependencies
      run: |
        sudo apt install -y ninja-build
        python tools/get_deps.py --board ${{ matrix.board }}

    - name: Build
      run: |
        cmake . -B _build -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DBOARD=${{ matrix.board }}
        cmake --build _build
